name: Build and Release JAR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Clean
      run: mvn clean

    - name: Validate
      run: mvn validate

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Package
      run: mvn package

    - name: Install
      run: mvn install

    - name: Set JAR Path and Rename
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        JAR_FILE="target/DeathSwap-${VERSION}.jar"
        mv target/*.jar $JAR_FILE

    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: DeathSwap-${VERSION}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
